custom_service_name: "Lightning CI required checker"
subprojects:

  # SECTION: pytorch_lightning

  - id: "pytorch_lightning: Tests workflow"
    paths:
      - ".actions/**"
      - ".github/workflows/ci-tests-pytorch.yml"
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "requirements/pytorch/**"
      - "src/lightning/pytorch/**"
      - "src/pytorch_lightning/*"
      - "tests/tests_pytorch/**"
      - "tests/legacy/**"
      - "pyproject.toml"  # includes pytest config
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "pl-cpu (macOS-11, lightning, 3.8, 1.11)"
      - "pl-cpu (macOS-11, lightning, 3.9, 1.12)"
      - "pl-cpu (macOS-11, lightning, 3.10, 1.13)"
      - "pl-cpu (macOS-11, lightning, 3.8, 1.11, oldest)"
      - "pl-cpu (ubuntu-20.04, lightning, 3.9, 1.11)"
      - "pl-cpu (ubuntu-20.04, lightning, 3.10, 1.12)"
      - "pl-cpu (ubuntu-20.04, lightning, 3.10, 1.13)"
      - "pl-cpu (ubuntu-20.04, lightning, 3.8, 1.11, oldest)"
      - "pl-cpu (windows-2022, lightning, 3.9, 1.11)"
      - "pl-cpu (windows-2022, lightning, 3.10, 1.12)"
      - "pl-cpu (windows-2022, lightning, 3.10, 1.13)"
      - "pl-cpu (windows-2022, lightning, 3.8, 1.11, oldest)"
      - "pl-cpu (slow, macOS-11, lightning, 3.8, 1.11)"
      - "pl-cpu (slow, ubuntu-20.04, lightning, 3.8, 1.11)"
      - "pl-cpu (slow, windows-2022, lightning, 3.8, 1.11)"
      - "pl-cpu (macOS-11, pytorch, 3.8, 1.13)"
      - "pl-cpu (ubuntu-20.04, pytorch, 3.8, 1.13)"
      - "pl-cpu (windows-2022, pytorch, 3.8, 1.13)"

  - id: "pytorch_lightning: Azure GPU"
    paths:
      - ".actions/**"
      - ".azure/gpu-tests-pytorch.yml"
      # only the azure GPU workflow runs the examples
      # all examples don't need to be added because they aren't used in CI, but these are
      - "examples/run_pl_examples.sh"
      - "examples/pl_basics/backbone_image_classifier.py"
      - "examples/pl_basics/autoencoder.py"
      - "requirements/pytorch/**"
      - "src/lightning/pytorch/**"
      - "src/pytorch_lightning/*"
      - "tests/tests_pytorch/**"
      - "pyproject.toml"  # includes pytest config
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "!requirements/docs.txt"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "pytorch-lightning (GPUs)"

  - id: "pytorch_lightning: Benchmarks"
    paths:
      - ".azure/gpu-benchmark.yml"
      - "tests/tests_pytorch/benchmarks/**"
      - "requirements/pytorch/**"
      - "!requirements/pytorch/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "pytorch-lightning.Benchmark"

  - id: "pytorch_lightning: Azure HPU"
    paths:
      - ".actions/**"
      - ".azure/hpu-tests.yml"
      - "examples/pl_hpu/mnist_sample.py"
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "requirements/pytorch/**"
      - "src/lightning/pytorch/**"
      - "src/pytorch_lightning/*"
      - "tests/tests_pytorch/**"
      - "pyproject.toml"  # includes pytest config
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "pytorch-lightning (HPUs)"

  - id: "pytorch_lightning: Azure IPU"
    paths:
      - ".actions/**"
      - ".azure/ipu-tests.yml"
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "requirements/pytorch/**"
      - "src/lightning/pytorch/**"
      - "src/pytorch_lightning/*"
      - "tests/tests_pytorch/**"
      - "pyproject.toml"  # includes pytest config
      - "!requirements/docs.txt"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "pytorch-lightning (IPUs)"

  # TODO: since this job has intermittent availability, it cannot be required
  #- id: "pytorch-lightning: TPU workflow"
  #  paths:
  #    - ".actions/**"
  #    - ".github/workflows/tpu-tests.yml"
  #    - "dockers/base-xla/*"
  #    - "requirements/fabric/**"
  #    - "src/lightning_fabric/**"
  #    - "tests/tests_fabric/**"
  #    - "requirements/pytorch/**"
  #    - "src/pytorch_lightning/**"
  #    - "tests/tests_pytorch/**"
  #    - "pyproject.toml"  # includes pytest config
  #    - "!requirements/*/docs.txt"
  #    - "!*.md"
  #    - "!**/*.md"
  #  checks:
  #    - "test-on-tpus"

  - id: "pytorch_lightning: Docs"
    paths:
      - "src/lightning/pytorch/**"
      - "src/pytorch_lightning/*"
      - "docs/source-pytorch/**"
      - ".actions/**"
      - ".github/workflows/docs-checks.yml"
      - "requirements/docs.txt"
      - "requirements/pytorch/**"
      - "setup.py"
      - "pyproject.toml"  # includes metadata used in the package creation
      - "!*.md"
      - "!**/*.md"
    checks:
      - "make-doctest (pytorch)"
      - "make-html (pytorch)"

  - id: "pytorch_lightning: Docker"
    paths:
      - ".actions/**"
      - ".github/workflows/ci-pytorch-dockers.yml"
      - "dockers/**"
      - "requirements/pytorch/**"
      - "requirements/fabric/**"
      - "environment.yml"
      - "setup.py"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "build-cuda (3.9, 1.11, 11.3.1)"
      - "build-cuda (3.9, 1.12, 11.6.1)"
      - "build-cuda (3.9, 1.13, 11.7.1)"
      - "build-hpu (1.5.0, 1.11.0)"
      - "build-ipu (3.9, 1.13)"
      - "build-NGC"
      - "build-pl (3.9, 1.11, 11.3.1)"
      - "build-pl (3.9, 1.12, 11.6.1)"
      - "build-pl (3.9, 1.13, 11.7.1)"
      - "build-xla (3.8, 1.12)"

  # SECTION: lightning_fabric

  - id: "lightning_fabric: CPU workflow"
    paths:
      - ".actions/**"
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "tests/tests_fabric/**"
      - "pyproject.toml"  # includes pytest config
      - ".github/workflows/ci-tests-fabric.yml"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "fabric-cpu (macOS-11, lightning, 3.8, 1.11)"
      - "fabric-cpu (macOS-11, lightning, 3.9, 1.12)"
      - "fabric-cpu (macOS-11, lightning, 3.10, 1.13)"
      - "fabric-cpu (macOS-11, lightning, 3.8, 1.11, oldest)"
      - "fabric-cpu (ubuntu-20.04, lightning, 3.9, 1.11)"
      - "fabric-cpu (ubuntu-20.04, lightning, 3.10, 1.12)"
      - "fabric-cpu (ubuntu-20.04, lightning, 3.10, 1.13)"
      - "fabric-cpu (ubuntu-20.04, lightning, 3.8, 1.11, oldest)"
      - "fabric-cpu (windows-2022, lightning, 3.9, 1.11)"
      - "fabric-cpu (windows-2022, lightning, 3.10, 1.12)"
      - "fabric-cpu (windows-2022, lightning, 3.10, 1.13)"
      - "fabric-cpu (windows-2022, lightning, 3.8, 1.11, oldest)"
      - "fabric-cpu (macOS-11, fabric, 3.8, 1.13)"
      - "fabric-cpu (ubuntu-20.04, fabric, 3.8, 1.13)"
      - "fabric-cpu (windows-2022, fabric, 3.8, 1.13)"

  - id: "lightning_fabric: Azure GPU"
    paths:
      - ".actions/**"
      - ".azure/gpu-tests-fabric.yml"
      - "examples/fabric/**"
      - "examples/run_fabric_examples.sh"
      - "tests/tests_fabric/run_standalone_*.sh"
      - "tests/tests_pytorch/run_standalone_tests.sh"  # used by Fabric through a symlink
      - "requirements/fabric/**"
      - "src/lightning/fabric/**"
      - "src/lightning_fabric/*"
      - "tests/tests_fabric/**"
      - "pyproject.toml"  # includes pytest config
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "lightning-fabric (GPUs)"

  # SECTION: lightning_app

  - id: "lightning_app: Tests workflow"
    paths:
      - ".actions/**"
      - ".github/workflows/ci-tests-app.yml"
      - "src/lightning/app/**"
      - "src/lightning_app/*"
      - "tests/tests_app/**"
      - "requirements/app/**"
      - "setup.py"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "app-pytest (macOS-11, lightning, 3.8, latest)"
      - "app-pytest (macOS-11, lightning, 3.8, oldest)"
      - "app-pytest (macOS-11, app, 3.9, latest)"
      - "app-pytest (ubuntu-20.04, lightning, 3.8, latest)"
      - "app-pytest (ubuntu-20.04, lightning, 3.8, oldest)"
      - "app-pytest (ubuntu-20.04, app, 3.9, latest)"
      - "app-pytest (windows-2022, lightning, 3.8, latest)"
      - "app-pytest (windows-2022, lightning, 3.8, oldest)"
      - "app-pytest (windows-2022, app, 3.8, latest)"

  - id: "lightning_app: Examples"
    paths:
      - ".actions/**"
      - ".github/workflows/ci-examples-app.yml"
      - "src/lightning/app/**"
      - "src/lightning_app/*"
      - "tests/integrations_app/**"
      - "!tests/integrations_app/flagship/**"
      - "examples/app_*/**"
      - "requirements/app/**"
      - "setup.py"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "app-examples (macOS-11, lightning, 3.9, latest)"
      - "app-examples (macOS-11, lightning, 3.9, oldest)"
      - "app-examples (macOS-11, app, 3.9, latest)"
      - "app-examples (ubuntu-20.04, lightning, 3.9, latest)"
      - "app-examples (ubuntu-20.04, lightning, 3.9, oldest)"
      - "app-examples (ubuntu-20.04, app, 3.9, latest)"
      - "app-examples (windows-2022, lightning, 3.9, latest)"
      - "app-examples (windows-2022, lightning, 3.9, oldest)"
      - "app-examples (windows-2022, app, 3.9, latest)"

  - id: "lightning: Flagships"
    paths:
      - ".github/workflows/_flagship-apps.yml"
      - ".github/workflows/ci-flagship-apps.yml"
      - "github/actions/prep-apps/action.yml"
      - "tests/integrations_app/flagship/**"
    checks:
      - "test-flagships / run-flagships (flashy, Lightning-Universe/Flashy-app)"

  - id: "lightning: Store"
    paths:
      - ".azure/app-cloud-store.yml"
      - "src/lightning/store/**"
      - "tests/tests_cloud/**"
    checks:
      - "Store.cloud (test_store Linux)"
      - "Store.cloud (test_store Mac)"
      - "Store.cloud (test_store Windows)"

  - id: "lightning_app: Azure"
    paths:
      - ".actions/**"
      - ".azure/app-cloud-e2e.yml"
      - "src/lightning/app/**"
      - "src/lightning_app/*"
      - "requirements/app/**"
      - "tests/integrations_app/**"
      - "!tests/integrations_app/flagship/**"
      - "setup.py"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "App.cloud-e2e"

  - id: "lightning_app: Docs"
    paths:
      - ".actions/**"
      - "src/lightning/app/**"
      - "src/lightning_app/*"
      - "docs/source-lit/**"
      - ".github/workflows/docs-checks.yml"
      - "requirements/docs.txt"
      - "requirements/app/**"
      - "setup.py"
      - "pyproject.toml"  # includes metadata used in the package creation
      - "!*.md"
      - "!**/*.md"
    checks:
      - "make-doctest (app)"
      - "make-html (app)"

  # SECTION: common

  - id: "mypy"
    paths:
      - ".actions/**"
      - ".github/workflows/code-checks.yml"
      - "requirements/**"
      - "src/**"
      - "pyproject.toml"  # includes mypy config
      - "!requirements/docs.txt"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "mypy"

  - id: "install"
    paths:
      - ".actions/**"
      - ".github/actions/pkg-check/*"
      - ".github/actions/pkg-install/*"
      - ".github/workflows/_build-packages.yml"
      - ".github/workflows/ci-pkg-install.yml"
      - "setup.py"
      - "src/**"
      - "requirements/**"
      - "!requirements/docs.txt"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
    checks:
      - "install-pkg (ubuntu-22.04, app, 3.8)"
      - "install-pkg (ubuntu-22.04, app, 3.10)"
      - "install-pkg (ubuntu-22.04, fabric, 3.8)"
      - "install-pkg (ubuntu-22.04, fabric, 3.10)"
      - "install-pkg (ubuntu-22.04, pytorch, 3.8)"
      - "install-pkg (ubuntu-22.04, pytorch, 3.10)"
      - "install-pkg (ubuntu-22.04, lightning, 3.8)"
      - "install-pkg (ubuntu-22.04, lightning, 3.10)"
      - "install-pkg (ubuntu-22.04, notset, 3.8)"
      - "install-pkg (ubuntu-22.04, notset, 3.10)"
      - "install-pkg (macOS-12, app, 3.8)"
      - "install-pkg (macOS-12, app, 3.10)"
      - "install-pkg (macOS-12, fabric, 3.8)"
      - "install-pkg (macOS-12, fabric, 3.10)"
      - "install-pkg (macOS-12, pytorch, 3.8)"
      - "install-pkg (macOS-12, pytorch, 3.10)"
      - "install-pkg (macOS-12, lightning, 3.8)"
      - "install-pkg (macOS-12, lightning, 3.10)"
      - "install-pkg (macOS-12, notset, 3.8)"
      - "install-pkg (macOS-12, notset, 3.10)"
      - "install-pkg (windows-2022, app, 3.8)"
      - "install-pkg (windows-2022, app, 3.10)"
      - "install-pkg (windows-2022, fabric, 3.8)"
      - "install-pkg (windows-2022, fabric, 3.10)"
      - "install-pkg (windows-2022, pytorch, 3.8)"
      - "install-pkg (windows-2022, pytorch, 3.10)"
      - "install-pkg (windows-2022, lightning, 3.8)"
      - "install-pkg (windows-2022, lightning, 3.10)"
      - "install-pkg (windows-2022, notset, 3.8)"
      - "install-pkg (windows-2022, notset, 3.10)"

  - id: "link-check"
    paths:
      - ".github/workflows/md-check-links.yml"
      - "**/*.md"
    checks:
      - "markdown-link-check"
